name: Checks
on: [push]

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
    - name: Print environment variables
      run: env

    - name: Print files
      run: ls -la

    - name: RUN TEST FILE
      run: python3 ./test.py
