name: Checks
on: [push]

jobs:
  first:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3

    steps:
    - name: Print environment variables
      run: env

    - name: RUN TEST FILE
      run: python3 test.py
